-- Published Darlington seed. Official / public sources only.
insert into public.sites (
  slug, name, site_type, stage, badge, county, state, mw, acres, applicant,
  lat, lng, source_url, source_label, summary, published
) values
(
  'robinson-solar-center',
  'Robinson Solar Center',
  'solar',
  'application',
  'official',
  'darlington',
  'SC',
  76,
  345,
  'Duke Energy Progress',
  34.417114,
  -80.17435,
  'https://www.duke-energy.com/RobinsonSolarCenter',
  'Duke Energy project page',
  '76 MWac solar PV and associated 230 kV tie on company-owned land next to Robinson Nuclear Plant and the Darlington CT plant.',
  true
),
(
  'lotus-solar',
  'Lotus Solar',
  'solar',
  'approved',
  'official',
  'darlington',
  'SC',
  75,
  644,
  'Lotus Solar, LLC (Pine Gate Renewables)',
  34.447832,
  -80.10356,
  'https://www.interconnection.fyi/eia/project/68337-lotus',
  'EIA-860M plant 68337',
  'Proposed 75 MW photovoltaic plant east of Hartsville. EIA: approvals received, not under construction. Listed COD October 1, 2027.',
  true
),
(
  'darlington-solar-llc',
  'Darlington Solar, LLC',
  'solar',
  'operating',
  'official',
  'darlington',
  'SC',
  10,
  null,
  'Darlington Solar, LLC',
  34.32,
  -79.917,
  'https://www.eia.gov/electricity/data/eia860/',
  'EIA-860 plant 60993',
  'Operating 10 MW photovoltaic plant at 808 E. Billy Farrow Hwy, Darlington.',
  true
),
(
  'hb-robinson',
  'H.B. Robinson Steam Electric Plant',
  'generation',
  'operating',
  'official',
  'darlington',
  'SC',
  null,
  null,
  'Duke Energy Progress',
  34.400556,
  -80.151389,
  'https://www.nrc.gov/docs/ML1915/ML19155A087.pdf',
  'NRC FSAR site location',
  'Operating generation on the southwest shore of Lake Robinson, northwest Darlington County.',
  true
),
(
  'tedder-solar',
  'Tedder Solar',
  'solar',
  'operating',
  'official',
  'darlington',
  'SC',
  2,
  null,
  'Tedder Solar',
  34.30181,
  -79.92446,
  'https://www.eia.gov/electricity/data/eia860/',
  'EIA-860 plant 62315',
  'Operating 2 MW photovoltaic plant near Rogers Road and Harry Byrd Highway, Darlington.',
  true
),
(
  'pit-stop-solar',
  'Pit Stop Solar',
  'solar',
  'approved',
  'official',
  'darlington',
  'SC',
  75,
  1100,
  'Pit Stop Solar, LLC',
  34.281528,
  -79.927611,
  'https://www.darcosc.com/government/county_council/recently_approved_ordinances.php',
  'Darlington County recently approved ordinances',
  'Utility-scale solar near Branhams Airport. FILOT 24-11 / MCIP 24-12 (July 1, 2024), ~75 MW, ~1,100 acres, ~$115M. February 2026 Planning Commission approval appealed as Deborah Martin et al. v. Darlington County et al., 2026CP1600286 (filed March 20, 2026).',
  true
)
on conflict (slug) do update set
  name = excluded.name,
  published = true,
  lat = excluded.lat,
  lng = excluded.lng,
  stage = excluded.stage,
  mw = excluded.mw,
  acres = excluded.acres,
  applicant = excluded.applicant,
  source_url = excluded.source_url,
  source_label = excluded.source_label,
  summary = excluded.summary;
