-- Published Darlington seed. Official / public sources only.
insert into public.sites (
  slug, name, site_type, stage, badge, county, state, mw, acres, applicant,
  lat, lng, source_url, source_label, summary, published
) values
(
  'robinson-solar-center',
  'Robinson Solar Center',
  'solar',
  'application',
  'official',
  'darlington',
  'SC',
  76,
  345,
  'Duke Energy Progress',
  34.417114,
  -80.17435,
  'https://www.duke-energy.com/RobinsonSolarCenter',
  'Duke Energy project page',
  '76 MWac solar PV and associated 230 kV tie on company-owned land next to Robinson Nuclear Plant and the Darlington CT plant.',
  true
),
(
  'lotus-solar',
  'Lotus Solar',
  'solar',
  'approved',
  'official',
  'darlington',
  'SC',
  75,
  644,
  'Lotus Solar, LLC (Pine Gate Renewables)',
  34.447832,
  -80.10356,
  'https://www.interconnection.fyi/eia/project/68337-lotus',
  'EIA-860M plant 68337',
  'Proposed 75 MW photovoltaic plant east of Hartsville. EIA: approvals received, not under construction. Listed COD October 1, 2027.',
  true
),
(
  'darlington-solar-llc',
  'Darlington Solar, LLC',
  'solar',
  'operating',
  'official',
  'darlington',
  'SC',
  10,
  null,
  'SunStrong Management',
  34.32,
  -79.917,
  'https://www.gridinfo.com/plant/darlington-solar-llc/60993',
  'EIA-860 plant 60993',
  'Operating 10 MW photovoltaic plant at 808 E. Billy Farrow Hwy, Darlington. First operation December 2016.',
  true
),
(
  'hb-robinson',
  'H.B. Robinson Steam Electric Plant',
  'generation',
  'operating',
  'official',
  'darlington',
  'SC',
  null,
  null,
  'Duke Energy Progress',
  34.400556,
  -80.151389,
  'https://www.nrc.gov/docs/ML1915/ML19155A087.pdf',
  'NRC FSAR site location',
  'Operating generation on the southwest shore of Lake Robinson, northwest Darlington County.',
  true
),
(
  'jefferson-solar',
  'Jefferson Solar',
  'solar',
  'operating',
  'official',
  'darlington',
  'SC',
  8.2,
  null,
  'Jefferson Solar',
  34.34957,
  -80.05812,
  'https://www.gridinfo.com/plant/jefferson-solar-sc/62233',
  'EIA-860 plant 62233',
  'Operating 8.2 MW photovoltaic plant off Briarwood Lane, Hartsville. First operation November 2022.',
  true
),
(
  'birch-solar',
  'Birch Solar',
  'solar',
  'operating',
  'official',
  'darlington',
  'SC',
  2,
  null,
  'Headwater Energy, LLC',
  34.26799,
  -79.86858,
  'https://www.gridinfo.com/plant/birch-solar/62185',
  'EIA-860 plant 62185',
  'Operating 2 MW photovoltaic plant off Woodstream Drive, Darlington. First operation February 2024.',
  true
),
(
  'chapman-solar',
  'Chapman Solar',
  'solar',
  'operating',
  'official',
  'darlington',
  'SC',
  2,
  null,
  'Headwater Energy, LLC',
  34.36982,
  -80.02481,
  'https://www.gridinfo.com/plant/chapman-solar/62186',
  'EIA-860 plant 62186',
  'Operating 2 MW photovoltaic plant in Hartsville. First operation November 2023.',
  true
),
(
  '1634-solar',
  '1634 Solar',
  'solar',
  'operating',
  'official',
  'darlington',
  'SC',
  2,
  null,
  '1634 Solar, LLC',
  34.3368,
  -80.08149,
  'https://www.gridinfo.com/plant/1634-solar/61935',
  'EIA-860 plant 61935',
  'Operating 2 MW photovoltaic plant south of Hartsville. First operation February 2021.',
  true
),
(
  'redwing-solar',
  'Redwing Solar',
  'solar',
  'operating',
  'official',
  'darlington',
  'SC',
  2,
  null,
  'Altus Power America Management, LLC',
  34.27441,
  -79.8875,
  'https://www.gridinfo.com/plant/redwing-solar/61946',
  'EIA-860 plant 61946',
  'Operating 2 MW photovoltaic plant at Timmonsville Highway and High, Darlington. First operation February 2019.',
  true
),
(
  'tedder-solar',
  'Tedder Solar',
  'solar',
  'operating',
  'official',
  'darlington',
  'SC',
  2,
  null,
  'Tedder Solar',
  34.30181,
  -79.92446,
  'https://www.eia.gov/electricity/data/eia860/',
  'EIA-860 plant 62315',
  'Operating 2 MW photovoltaic plant near Rogers Road and Harry Byrd Highway, Darlington.',
  true
),
(
  'watauga-solar',
  'Watauga Solar',
  'solar',
  'operating',
  'official',
  'darlington',
  'SC',
  2,
  null,
  'Altus Power America Management, LLC',
  34.52394,
  -79.84462,
  'https://www.gridinfo.com/plant/watauga-solar/61951',
  'EIA-860 plant 61951',
  'Operating 2 MW photovoltaic plant at Burlington Drive and West Depot Street, Society Hill. First operation March 2019.',
  true
),
(
  'ashley-solar',
  'Ashley Solar',
  'solar',
  'operating',
  'official',
  'darlington',
  'SC',
  2,
  null,
  'Ashley Solar (SC)',
  34.26891,
  -79.87255,
  'https://www.gridinfo.com/plant/ashley-solar-sc/62179',
  'EIA-860 plant 62179',
  'Operating 2 MW photovoltaic plant south of Darlington. First operation January 2025.',
  true
),
(
  'marshall-solar',
  'Marshall Solar',
  'solar',
  'operating',
  'official',
  'darlington',
  'SC',
  2,
  null,
  'Marshall Solar',
  34.37191,
  -80.02161,
  'https://www.gridinfo.com/plant/marshall-solar/62238',
  'EIA-860 plant 62238',
  'Operating 2 MW photovoltaic plant west of East Carolina Avenue, Hartsville. First operation July 2022.',
  true
),
(
  'luz-solar',
  'Luz Solar',
  'solar',
  'operating',
  'official',
  'darlington',
  'SC',
  1.1,
  null,
  'Luz Solar',
  34.3702,
  -80.0273,
  'https://www.gridinfo.com/plant/luz-solar/62236',
  'EIA-860 plant 62236',
  'Operating 1.1 MW photovoltaic plant at West Billy Farrow Highway and East Carolina, Hartsville. First operation December 2024.',
  true
),
(
  'pit-stop-solar',
  'Pit Stop Solar',
  'solar',
  'approved',
  'official',
  'darlington',
  'SC',
  75,
  1100,
  'Pit Stop Solar, LLC',
  34.281528,
  -79.927611,
  'https://www.darcosc.com/government/county_council/recently_approved_ordinances.php',
  'Darlington County recently approved ordinances',
  'Utility-scale solar near Branhams Airport. FILOT 24-11 / MCIP 24-12 (July 1, 2024), ~75 MW, ~1,100 acres, ~$115M. February 2026 Planning Commission approval appealed as Deborah Martin et al. v. Darlington County et al., 2026CP1600286 (filed March 20, 2026).',
  true
)
on conflict (slug) do update set
  name = excluded.name,
  published = true,
  lat = excluded.lat,
  lng = excluded.lng,
  stage = excluded.stage,
  mw = excluded.mw,
  acres = excluded.acres,
  applicant = excluded.applicant,
  source_url = excluded.source_url,
  source_label = excluded.source_label,
  summary = excluded.summary;
