import type { Site } from "./types";

export const SEED_CORE: Site[] = [
  { slug: "robinson-solar-center", name: "Robinson Solar Center", siteType: "solar", stage: "application", badge: "official", county: "darlington", state: "SC", mw: 76, acres: 345, applicant: "Duke Energy Progress", lat: 34.417114, lng: -80.17435, sourceUrl: "https://www.duke-energy.com/RobinsonSolarCenter", sourceLabel: "Duke Energy project page", summary: "76 MWac solar PV and 230 kV tie on company-owned land next to Robinson Nuclear Plant and the Darlington CT plant. Construction targeted late 2026 or early 2027." },
  { slug: "lotus-solar", name: "Lotus Solar", siteType: "solar", stage: "approved", badge: "official", county: "darlington", state: "SC", mw: 75, acres: 644, applicant: "Lotus Solar, LLC (Pine Gate Renewables)", lat: 34.447832, lng: -80.10356, sourceUrl: "https://www.interconnection.fyi/eia/project/68337-lotus", sourceLabel: "EIA-860M plant 68337", summary: "Proposed 75 MW photovoltaic plant east of Hartsville. EIA: approvals received, not under construction. Listed COD October 1, 2027." },
  { slug: "darlington-solar-llc", name: "Darlington Solar, LLC", siteType: "solar", stage: "operating", badge: "official", county: "darlington", state: "SC", mw: 10, applicant: "SunStrong Management", lat: 34.32, lng: -79.917, sourceUrl: "https://www.gridinfo.com/plant/darlington-solar-llc/60993", sourceLabel: "EIA-860 plant 60993", summary: "Operating 10 MW photovoltaic plant at 808 E. Billy Farrow Hwy, Darlington. First operation December 2016." },
  { slug: "hb-robinson", name: "H.B. Robinson Steam Electric Plant", siteType: "generation", stage: "operating", badge: "official", county: "darlington", state: "SC", applicant: "Duke Energy Progress", lat: 34.400556, lng: -80.151389, sourceUrl: "https://www.nrc.gov/docs/ML1915/ML19155A087.pdf", sourceLabel: "NRC FSAR site location", summary: "Operating generation on the southwest shore of Lake Robinson. Neighbor context for Robinson Solar Center." },
  { slug: "jefferson-solar", name: "Jefferson Solar", siteType: "solar", stage: "operating", badge: "official", county: "darlington", state: "SC", mw: 8.2, applicant: "Jefferson Solar", lat: 34.34957, lng: -80.05812, sourceUrl: "https://www.gridinfo.com/plant/jefferson-solar-sc/62233", sourceLabel: "EIA-860 plant 62233", summary: "Operating 8.2 MW photovoltaic plant off Briarwood Lane, Hartsville. First operation November 2022." },
  { slug: "birch-solar", name: "Birch Solar", siteType: "solar", stage: "operating", badge: "official", county: "darlington", state: "SC", mw: 2, applicant: "Headwater Energy, LLC", lat: 34.26799, lng: -79.86858, sourceUrl: "https://www.gridinfo.com/plant/birch-solar/62185", sourceLabel: "EIA-860 plant 62185", summary: "Operating 2 MW photovoltaic plant off Woodstream Drive, Darlington. First operation February 2024." },
  { slug: "chapman-solar", name: "Chapman Solar", siteType: "solar", stage: "operating", badge: "official", county: "darlington", state: "SC", mw: 2, applicant: "Headwater Energy, LLC", lat: 34.36982, lng: -80.02481, sourceUrl: "https://www.gridinfo.com/plant/chapman-solar/62186", sourceLabel: "EIA-860 plant 62186", summary: "Operating 2 MW photovoltaic plant in Hartsville. First operation November 2023." },
  { slug: "1634-solar", name: "1634 Solar", siteType: "solar", stage: "operating", badge: "official", county: "darlington", state: "SC", mw: 2, applicant: "1634 Solar, LLC", lat: 34.3368, lng: -80.08149, sourceUrl: "https://www.gridinfo.com/plant/1634-solar/61935", sourceLabel: "EIA-860 plant 61935", summary: "Operating 2 MW photovoltaic plant south of Hartsville. First operation February 2021." },
  { slug: "redwing-solar", name: "Redwing Solar", siteType: "solar", stage: "operating", badge: "official", county: "darlington", state: "SC", mw: 2, applicant: "Altus Power America Management, LLC", lat: 34.27441, lng: -79.8875, sourceUrl: "https://www.gridinfo.com/plant/redwing-solar/61946", sourceLabel: "EIA-860 plant 61946", summary: "Operating 2 MW photovoltaic plant at Timmonsville Highway and High, Darlington. First operation February 2019." },
  { slug: "tedder-solar", name: "Tedder Solar", siteType: "solar", stage: "operating", badge: "official", county: "darlington", state: "SC", mw: 2, applicant: "Tedder Solar", lat: 34.30181, lng: -79.92446, sourceUrl: "https://www.eia.gov/electricity/data/eia860/", sourceLabel: "EIA-860 plant 62315", summary: "Operating 2 MW photovoltaic plant near Rogers Road and Harry Byrd Highway, Darlington. First operation December 2021." },
  { slug: "watauga-solar", name: "Watauga Solar", siteType: "solar", stage: "operating", badge: "official", county: "darlington", state: "SC", mw: 2, applicant: "Altus Power America Management, LLC", lat: 34.52394, lng: -79.84462, sourceUrl: "https://www.gridinfo.com/plant/watauga-solar/61951", sourceLabel: "EIA-860 plant 61951", summary: "Operating 2 MW photovoltaic plant at Burlington Drive and West Depot Street, Society Hill. First operation March 2019." },
  { slug: "ashley-solar", name: "Ashley Solar", siteType: "solar", stage: "operating", badge: "official", county: "darlington", state: "SC", mw: 2, applicant: "Ashley Solar (SC)", lat: 34.26891, lng: -79.87255, sourceUrl: "https://www.gridinfo.com/plant/ashley-solar-sc/62179", sourceLabel: "EIA-860 plant 62179", summary: "Operating 2 MW photovoltaic plant south of Darlington. First operation January 2025." },
  { slug: "marshall-solar", name: "Marshall Solar", siteType: "solar", stage: "operating", badge: "official", county: "darlington", state: "SC", mw: 2, applicant: "Marshall Solar", lat: 34.37191, lng: -80.02161, sourceUrl: "https://www.gridinfo.com/plant/marshall-solar/62238", sourceLabel: "EIA-860 plant 62238", summary: "Operating 2 MW photovoltaic plant west of East Carolina Avenue, Hartsville. First operation July 2022." },
  { slug: "luz-solar", name: "Luz Solar", siteType: "solar", stage: "operating", badge: "official", county: "darlington", state: "SC", mw: 1.1, applicant: "Luz Solar", lat: 34.3702, lng: -80.0273, sourceUrl: "https://www.gridinfo.com/plant/luz-solar/62236", sourceLabel: "EIA-860 plant 62236", summary: "Operating 1.1 MW photovoltaic plant at West Billy Farrow Highway and East Carolina, Hartsville. First operation December 2024." },
  { slug: "pit-stop-solar", name: "Pit Stop Solar", siteType: "solar", stage: "approved", badge: "official", county: "darlington", state: "SC", mw: 75, acres: 1100, applicant: "Pit Stop Solar, LLC", lat: 34.281528, lng: -79.927611, sourceUrl: "https://www.darcosc.com/government/county_council/recently_approved_ordinances.php", sourceLabel: "Darlington County recently approved ordinances", summary: "Utility-scale solar near Branhams Airport. FILOT 24-11 / MCIP 24-12 (July 1, 2024), ~75 MW, ~1,100 acres. February 2026 Planning Commission approval appealed as Deborah Martin et al. v. Darlington County et al., 2026CP1600286." },
];
