import type { Site } from "./types";

/** Approved and in-planning Darlington solar with public coordinates. */
export const PLANNING_SITES: Site[] = [
  {
    slug: "bk-solar",
    name: "B & K Solar",
    siteType: "solar",
    stage: "approved",
    badge: "official",
    county: "darlington",
    state: "SC",
    mw: 74.9,
    acres: 456,
    applicant: "B & K Solar, LLC (energyRe / Southern Current)",
    lat: 34.4234,
    lng: -80.0621,
    sourceUrl: "https://www.interconnection.fyi/eia/plant/62181",
    sourceLabel: "EIA-860M plant 62181",
    summary:
      "Planned 74.9 MW photovoltaic plant near North Hartsville / Antioch (Ousleydale Road). EIA proposed COD November 1, 2026. County FILOT ordinance 23-08 replaced the 2018 B&K fee agreement. DEP PPA accepted March 7, 2024; interconnection work is the Patrick Highway 230 kV switching station. Point from EIA / GEM.",
  },
  {
    slug: "culpepper-solar",
    name: "Culpepper Solar",
    siteType: "solar",
    stage: "approved",
    badge: "official",
    county: "darlington",
    state: "SC",
    mw: 74.9,
    acres: 677,
    applicant: "Culpepper Solar, LLC (energyRe / Southern Current)",
    lat: 34.465864,
    lng: -79.96044,
    sourceUrl: "https://www.interconnection.fyi/eia/project/62221-33",
    sourceLabel: "EIA-860M plant 62221",
    summary:
      "74.9 MW photovoltaic plant near Society Hill (Sherrills Mill Road and Byrdtown Road). EIA status T: regulatory approvals received, not under construction. Listed COD November 1, 2027. County FILOT ordinance 23-05. DEP PPA in 2024; PSC Docket 2026-53-E covers the Byrdtown Road 230 kV fold-in. Point from EIA Form 860.",
  },
  {
    slug: "rollins-solar",
    name: "Rollins Solar",
    siteType: "solar",
    stage: "approved",
    badge: "official",
    county: "darlington",
    state: "SC",
    mw: 74.9,
    acres: 495,
    applicant: "Rollins Solar, LLC (energyRe / Southern Current)",
    lat: 34.3536,
    lng: -80.0162,
    sourceUrl: "https://www.gem.wiki/Rollins_Solar",
    sourceLabel: "EIA-860 / GEM — Rollins Solar",
    summary:
      "Planned 74.9 MW photovoltaic plant off Flinn Road, Hartsville / Bethel. County FILOT ordinance 23-06 replaced the 2018 Rollins fee agreement. Cleanview listed COD November 2027. Point from EIA / GEM.",
  },
  {
    slug: "ross-solar",
    name: "Ross Solar",
    siteType: "solar",
    stage: "approved",
    badge: "official",
    county: "darlington",
    state: "SC",
    mw: 74.9,
    acres: 1056,
    applicant: "Ross Solar, LLC (energyRe / Southern Current)",
    lat: 34.444756,
    lng: -79.851725,
    sourceUrl: "https://www.gem.wiki/Ross_Solar",
    sourceLabel: "EIA-860 plant 62296",
    summary:
      "Planned 74.9 MW photovoltaic plant at Gandy Siding Road and Society Hill, Dovesville / Society Hill. County FILOT ordinance 23-09. Cleanview listed COD November 2027. Point from EIA Form 860.",
  },
  {
    slug: "geb-solar",
    name: "GEB Solar",
    siteType: "solar",
    stage: "approved",
    badge: "official",
    county: "darlington",
    state: "SC",
    mw: 50,
    acres: 363,
    applicant: "GEB Solar, LLC (energyRe / Southern Current)",
    lat: 34.412367,
    lng: -80.04192,
    sourceUrl: "https://www.interconnection.fyi/eia/project/62217-40",
    sourceLabel: "EIA-860M plant 62217",
    summary:
      "Planned 50 MW photovoltaic plant near North Hartsville / Antioch Road. EIA status T: approvals received, not under construction. Listed COD November 1, 2028. County FILOT ordinance 23-07. Point from EIA Form 860.",
  },
  {
    slug: "ip-solar",
    name: "IP Solar",
    siteType: "solar",
    stage: "approved",
    badge: "official",
    county: "darlington",
    state: "SC",
    acres: 707,
    applicant: "IP Solar, LLC (Ampyr Energy US)",
    lat: 34.402377,
    lng: -79.895064,
    sourceUrl: "https://www.darcosc.com/government/county_council/recently_approved_ordinances.php",
    sourceLabel: "Darlington County recently approved ordinances",
    summary:
      "Utility-scale solar near Honeysuckle Road and Running Brook Road, Dovesville. County Council adopted FILOT ordinance 25-17 and MCIP ordinance 25-18. January 7, 2025 first reading named tax parcels 050-00-01-004, 073-00-01-069, 074-00-01-001, and 074-00-01-074. A May 2026 county list put the project at 706.69 acres. Pin is the Dovesville hamlet — not a surveyed array centroid.",
  },
  {
    slug: "stripe-solar",
    name: "Stripe Solar",
    siteType: "solar",
    stage: "application",
    badge: "official",
    county: "darlington",
    state: "SC",
    acres: 418,
    applicant: "Stripe Solar, LLC (Palladium Energy)",
    lat: 34.35316,
    lng: -80.1394,
    sourceUrl: "https://wpde.com/news/local/darlington-county-neighbors-push-back-against-proposed-417-acre-solar-project-palladium-energy-solar-panels-backyards-rural-community-clyde-road",
    sourceLabel: "WPDE — Stripe Solar / Clyde Road",
    summary:
      "Proposed 417.80-acre solar farm off Clyde Road / Deer Run Drive in the Kellytown community, developed by Jacksonville-based Palladium Energy. WPDE (Aug. 9–31, 2026) reports the project remains in county planning, with neighbor opposition and survey work on site. No EIA plant ID found as of this pass. Pin is the Kellytown hamlet — not a surveyed array centroid.",
  },
];
