import type { Site } from "./types";

/** Approved / in-planning Darlington solar with public coordinates. */
export const SEED_PLANNED: Site[] = [
  {
    slug: "bk-solar",
    name: "B & K Solar",
    siteType: "solar",
    stage: "approved",
    badge: "official",
    county: "darlington",
    state: "SC",
    mw: 74.9,
    acres: 456,
    applicant: "B & K Solar, LLC (energyRe / Southern Current)",
    lat: 34.423425,
    lng: -80.06213,
    sourceUrl: "https://www.interconnection.fyi/eia/project/62181-23",
    sourceLabel: "EIA-860M plant 62181",
    summary:
      "Planned 74.9 MW photovoltaic plant near North Hartsville / Antioch. EIA status T — regulatory approvals received, not under construction. Proposed commercial operation November 1, 2026. Interconnects to Duke Energy Progress at the planned Patrick Highway Solar 230 kV switching station. PSC Docket 2024-36-E accepted the DEP / B&K Solar PPA. DEP reported substation construction started in the December 31, 2025 quarterly update. Point from EIA Form 860.",
    notes: [
      "GEM lists Southern Current LLC as owner. Keep the applicant field as B & K Solar, LLC with the parent noted in parentheses.",
      "County seed acreage 456 is the figure used in the SQL/geojson pass — not a surveyed array footprint.",
      "Transmission work on the Patrick Highway switching station is not array construction. EIA still lists the generator as not under construction.",
    ],
    documents: [
      { title: "EIA-860M — B & K Solar plant 62181 / generator 23", url: "https://www.interconnection.fyi/eia/project/62181-23" },
      { title: "Global Energy Monitor — B & K Solar", url: "https://www.gem.wiki/B_&_K_Solar" },
      { title: "DEP quarterly update — Patrick Highway substation construction started", url: "https://dms.psc.sc.gov/Attachments/Matter/a3767bf5-0faf-412b-9c3f-095522008b26", postedOn: "2025-12-31" },
    ],
  },
  {
    slug: "culpepper-solar",
    name: "Culpepper Solar",
    siteType: "solar",
    stage: "approved",
    badge: "official",
    county: "darlington",
    state: "SC",
    mw: 74.9,
    acres: 677,
    applicant: "Culpepper Solar, LLC (energyRe / Southern Current)",
    lat: 34.465864,
    lng: -79.96044,
    sourceUrl: "https://www.interconnection.fyi/eia/project/62221-33",
    sourceLabel: "EIA-860M plant 62221",
    summary:
      "Planned 74.9 MW photovoltaic plant near Society Hill. EIA status T — regulatory approvals received, not under construction. Listed commercial operation November 1, 2027. Interconnects to Duke Energy Progress. Point from EIA Form 860.",
    documents: [
      { title: "EIA-860M — Culpepper Solar plant 62221 / generator 33", url: "https://www.interconnection.fyi/eia/project/62221-33" },
      { title: "Global Energy Monitor — Culpepper Solar", url: "https://www.gem.wiki/Culpepper_Solar" },
    ],
  },
  {
    slug: "rollins-solar",
    name: "Rollins Solar",
    siteType: "solar",
    stage: "approved",
    badge: "official",
    county: "darlington",
    state: "SC",
    mw: 74.9,
    acres: 495,
    applicant: "Rollins Solar, LLC (energyRe / Southern Current)",
    lat: 34.3536,
    lng: -80.0162,
    sourceUrl: "https://www.gem.wiki/Rollins_Solar",
    sourceLabel: "EIA-860 / GEM — Rollins Solar plant 62295",
    summary:
      "Planned 74.9 MW photovoltaic plant near Hartsville / Bethel. EIA plant 62295. GEM commissioning year 2027. Point from EIA / Global Energy Monitor.",
    documents: [
      { title: "EIA-860 — Rollins Solar plant 62295", url: "https://www.interconnection.fyi/eia/plant/62295" },
      { title: "Global Energy Monitor — Rollins Solar", url: "https://www.gem.wiki/Rollins_Solar" },
    ],
  },
  {
    slug: "ross-solar",
    name: "Ross Solar",
    siteType: "solar",
    stage: "approved",
    badge: "official",
    county: "darlington",
    state: "SC",
    mw: 74.9,
    acres: 1056,
    applicant: "Ross Solar, LLC (energyRe / Southern Current)",
    lat: 34.444756,
    lng: -79.851725,
    sourceUrl: "https://www.gem.wiki/Ross_Solar",
    sourceLabel: "EIA-860 plant 62296",
    summary:
      "Planned 74.9 MW photovoltaic plant at Gandy Siding Road and Society Hill. EIA plant 62296. GEM commissioning year 2027. Point from EIA Form 860.",
    documents: [
      { title: "EIA-860 — Ross Solar plant 62296", url: "https://www.interconnection.fyi/eia/plant/62296" },
      { title: "Global Energy Monitor — Ross Solar", url: "https://www.gem.wiki/Ross_Solar" },
    ],
  },
  {
    slug: "geb-solar",
    name: "GEB Solar",
    siteType: "solar",
    stage: "approved",
    badge: "official",
    county: "darlington",
    state: "SC",
    mw: 50,
    acres: 363,
    applicant: "GEB Solar, LLC (energyRe / Southern Current)",
    lat: 34.412367,
    lng: -80.04192,
    sourceUrl: "https://www.interconnection.fyi/eia/project/62217-40",
    sourceLabel: "EIA-860M plant 62217",
    summary:
      "Planned 50 MW photovoltaic plant near Antioch Road / North Hartsville. EIA status T — regulatory approvals received, not under construction. Listed commercial operation November 1, 2028. Point from EIA Form 860.",
    documents: [
      { title: "EIA-860M — GEB Solar plant 62217 / generator 40", url: "https://www.interconnection.fyi/eia/project/62217-40" },
    ],
  },
  {
    slug: "ip-solar",
    name: "IP Solar",
    siteType: "solar",
    stage: "approved",
    badge: "official",
    county: "darlington",
    state: "SC",
    acres: 707,
    applicant: "IP Solar, LLC (Ampyr Energy US)",
    lat: 34.402377,
    lng: -79.895064,
    sourceUrl: "https://www.darcosc.com/government/county_council/recently_approved_ordinances.php",
    sourceLabel: "Darlington County recently approved ordinances",
    summary:
      "Utility-scale solar near Honeysuckle Road and Running Brook Road / Dovesville. County FILOT ordinance 25-17 and MCIP ordinance 25-18. No EIA-860 plant ID found as of this pass. Pin is the Dovesville hamlet — not a surveyed array centroid.",
    notes: [
      "No public MW figure in EIA-860 as of Sept. 2, 2026. Do not invent capacity.",
      "707 acres is the county-list figure carried in the SQL seed.",
    ],
    documents: [
      { title: "Darlington County recently approved ordinances", url: "https://www.darcosc.com/government/county_council/recently_approved_ordinances.php" },
      { title: "Darlington County official solar GIS map", url: "https://www.arcgis.com/home/item.html?id=c62ede3f6e1a47068d133ed8edd2781c" },
    ],
  },
  {
    slug: "stripe-solar",
    name: "Stripe Solar",
    siteType: "solar",
    stage: "application",
    badge: "official",
    county: "darlington",
    state: "SC",
    acres: 418,
    applicant: "Stripe Solar, LLC (Palladium Energy)",
    lat: 34.35316,
    lng: -80.1394,
    sourceUrl: "https://wpde.com/news/local/darlington-county-neighbors-push-back-against-proposed-417-acre-solar-project-palladium-energy-solar-panels-backyards-rural-community-clyde-road",
    sourceLabel: "WPDE — Stripe Solar / Clyde Road",
    summary:
      "Proposed ~418-acre utility-scale solar farm off Clyde Road / Deer Run Drive in the Kellytown community. Developer is Jacksonville-based Palladium Energy. WPDE (Aug. 9 and Aug. 30, 2026) reports the project is still in county planning, with neighbor opposition and a proposed nine-month solar/wind moratorium before County Council. Pin is the Kellytown hamlet — not a surveyed array centroid. No EIA-860 plant ID or public MW figure as of this pass.",
    notes: [
      "WPDE: one of more than 30 solar developments Darlington County leaders have in planning or negotiation.",
      "County Council second reading on the moratorium ordinance was scheduled for September 10, 2026 at the Annex.",
    ],
    documents: [
      { title: "WPDE — neighbors push back against 417-acre Stripe Solar (Aug. 9, 2026)", url: "https://wpde.com/news/local/darlington-county-neighbors-push-back-against-proposed-417-acre-solar-project-palladium-energy-solar-panels-backyards-rural-community-clyde-road", postedOn: "2026-08-09" },
      { title: "WPDE — Clyde Road rally and proposed moratorium (Aug. 30, 2026)", url: "https://wpde.com/news/local/darlington-county-neighbors-rally-against-proposed-417-acre-solar-farm-strengthen-regulations-local-farmers-florida-based-palladium-energy-stripe-solar-llc-moratorium-wind-projects", postedOn: "2026-08-30" },
      { title: "Darlington County official solar GIS map", url: "https://www.arcgis.com/home/item.html?id=c62ede3f6e1a47068d133ed8edd2781c" },
    ],
  },
];
